### ISSUE TITLE
how to configure report portal to display JBehave BDD scenarios count instead of steps count

### ISSUE THREAD

**Issue by udaygadamsetty** [reportportal/agent-java-jbehave#36]
I tried all the internet but couldn't find a way to display statistics on the reportportal based on jbehave bdd scenarios instead of steps.  I am using report portal jbehave plugin [agent-java-jbehave] v4.2.0. Using ReportPortalViewGenerator from my jbehave runner.
Any help on configuring jbehave or report portal would be highly appreciated.
Thanks in advance.

**Comment by udaygadamsetty** [comment]
> it misses documentation,
> but we plan to focus on all java integrations next months

Was this ever fixed? I still have this as open issue.

**Comment by HardNorth** [comment]
The issue caused by outdated version of the agent, please use the latest one: https://github.com/reportportal/agent-java-jbehave/releases

For your case please use `ReportPortalScenarioFormat.INSTANCE` in JBehave initialization of formatters:
https://github.com/reportportal/agent-java-jbehave/blob/develop/README.md#test-runner-class
